### ISSUE TITLE
Use reduced permissions

### ISSUE THREAD

**Issue by willglynn** [cdzombak/OpenList#4]
`manifest.json` currently declares that the `tabs` permission is required, and as-written, it is. However, [this doesn't seem necessary for the core purpose of the extension](https://developer.chrome.com/extensions/permission_warnings#warnings):

> Note: As of Google Chrome 7, you no longer need to specify the "tabs" permission just to call `chrome.tabs.create()` or `chrome.tabs.update()`.

I'd rather install OpenList without agreeing that it can "Access your tabs and browsing activity", though the current (window-and-tab-reading) functionality could be preserved [on an optional basis](https://developer.chrome.com/extensions/permissions).

**Comment by cdzombak** [comment]
To present a list of currently-open tabs, we need to call `chrome.tabs.getAllInWindow` (see https://github.com/cdzombak/OpenList/blob/master/extension/openlist-popup.js#L3), which _does_ require that permission IIRC.

Please let me know if I'm missing something here (always possible).

**Comment by willglynn** [comment]
Yes, that's my read as well. I'm suggesting that OpenList work by default with reduced permissions – without the ability to read current tabs – and instead bind that functionality to a user-initiated action which would prompt for increased permissions. Something like:

``` javascript
chrome.permissions.contains({permissions: ['tabs']}, function(result) {
  if (result) {
    // get the list of tabs
    // …

  } else {
    // the user hasn't granted "Access your tabs and browsing activity"
    displayReadCurrentTabsButton();
  }
});

function displayReadCurrentTabsButton() {
  // …
  button.bind('click', function() {
    chrome.permissions.request({permissions: ['tabs']}, function(granted) {
      // …
    })
  });
}
```

**Comment by cdzombak** [comment]
I see. I think my preferred implementation would ask for permission the first time the extension is opened, so we don't have the added complexity of another link/button that the user has to use to explicitly trigger that flow.

That said, I've been using Safari pretty much full time lately, so I haven't been improving this extension for the last few months. If you'd like to submit a PR that moves in this direction, I'd appreciate it — go for it. Otherwise, I don't think I have time to act on it for the next couple weeks; lots of travel is on my calendar for June.

**Comment by cdzombak** [comment]
Sorry; as noted above, I'm using Safari full time and don't have time to make major changes to this extension. If anyone wants to make a pull request for this change, I'll review it, though I still think we'd need to consider how it affects the UI:

> I think my preferred implementation would ask for permission the first time the extension is opened, so we don't have the added complexity of another link/button that the user has to use to explicitly trigger that flow.
