### ISSUE TITLE
OpenList Issue - Chrome Extension Error

### ISSUE THREAD

**Issue by dehnlarson** [cdzombak/OpenList#5]
When I try to use this Chrome extension to open www.google.com, it provides me with an error (see attached screenshot). Do you have any recommendations?

![2014-06-05_1056](https://cloud.githubusercontent.com/assets/7806580/3189225/aa1d95aa-ecc1-11e3-8d79-fae711ea0b90.png)

**Comment by cdzombak** [comment]
@dehnlarson what exactly did you put into the OpenList box? Was it `www.google.com` or `http://www.google.com`? From the screenshot it looks like you tried the former, which isn't a valid URL.
