### ISSUE TITLE
gist /dropbox integration?

### ISSUE THREAD

**Issue by neslekkim** [cdzombak/OpenList#6]
Could it be possible to integrate with github gist, or dropbox, to save and restore urls to these stores?
I often have lots of chrome instances and tabs open, and would like to save all for reboot etc, now I'm going through each instance and getting the urls via openlist, and storing it manually that way.

**Comment by cdzombak** [comment]
> Could it be possible to integrate with github gist, or dropbox, to save and restore urls to these stores?

In theory, yes. But from a development perspective that would add some really significant complexity to an incredibly simple extension. I'm now using Safari full time, and as such I don't have time to add this to this extension.

**Comment by MrSlimbrowser** [comment]
6 years later it would still be a nice to have 😛 
If I understand correctly chrome got the [chrome.storage "API to store, retrieve, and track changes to user data"](https://developer.chrome.com/extensions/storage) that can also use chrome sync features. Should be a lot easier to implement compared to the requested services but looking at the current code it would still be a big chunk. But maybe it's worth thinking about anyway.
